apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdBackup
metadata:
  name: etcd-cluster-backup
  namespace: my-etcd
  annotations:
    - etcd.database.coreos.com/scope: clusterwide
spec:
  etcdEndpoints:
    - "http://etcd-cluster-client.my-etcd.svc:2379/"
  storageType: S3
  s3:
    endpoint: "http://default.svc.cluster.local:9000/"
    path: "minio-service/foo/etcdbackup"
    awsSecret: aws
