apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdRestore
metadata:
  name: etcd-cluster
  namespace: my-etcd
  annotations:
    - etcd.database.coreos.com/scope: clusterwide
spec:
  etcdCluster:
    name: etcd-cluster
  backupStorageType: S3
  s3:
    endpoint: "https://s3.eu-west-2.amazonaws.com/"
    path: "operators/etcd/etcd.backup"
    awsSecret: aws

